config/routes.rb
HarvestApp::Application.routes.draw do
  resources :reports, :as => "reports", :controller => "reports" 

  
  root :to => "reports#index"
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  require 'csv'
 

  def index
    #show the login page
  end
  
  def create
    #fetch and display the report
    @connection=Harvest.new(params[:report][:company], params[:report][:login], params[:report][:password])
    @connection.do_connect

    if @connection
      session[:login_info] = {:login => params[:report][:login], :company => params[:report][:company], :password =>   params[:report][:password]}
    end


    @company = @connection.company
    Rails.logger.info "company is #{@company.inspect}"
    response = @connection.request "/clients", :get
    clients = JSON.parse(response.body)
    @retrieved_clients = []
    clients.each do |client|
      @retrieved_clients << [client["client"]["id"],client["client"]["name"]]
    end
    @invoice_details = []
    
    @retrieved_clients.each do |rc|
      response = @connection.request "/invoices?client=#{rc[0].to_s}" , :get
      invoices = JSON.parse(response.body)
      
      invoices.each do |invoice|
       due_date = invoice["doc"]["due_at"].to_date
       invoice_id = invoice["doc"]["id"]
       
       response = @connection.request "/invoices/#{invoice_id}", :get
       puts "\n\n*** full invoice: #{JSON.parse(response.body).inspect} ***\n\n"
      @full_invoice = JSON.parse(response.body)["doc"]["csv_line_items"]
     
       if 1.weeks.ago.to_date > due_date 
         @invoice_details << {:id => invoice["doc"]["id"], :client_id => invoice["doc"]["client_id"], :name => rc[1], :status => "overdue", :invoice_number => invoice["doc"]["number"], :total_amount => invoice["doc"]["amount"], :full_invoice =>  @full_invoice}
       else
        @invoice_details << {:id => invoice["doc"]["id"], :client_id => invoice["doc"]["client_id"],:name =>rc[1], :status => "current", :invoice_number => invoice["doc"]["number"], :total_amount => invoice["doc"]["amount"] , :full_invoice =>  @full_invoice}
       end
       
    
      end
    end
  end
  
  def show
  
    @connection=Harvest.new(session[:login_info][:company], session[:login_info][:login], session[:login_info][:password])
    @connection.do_connect
    @company = @connection.company

    response = @connection.request "/invoices/#{params[:id]}", :get
    @full_invoice = JSON.parse(response.body)["doc"]
    @line_items = []
    line = 0
    @full_invoice["csv_line_items"].each do |line_item|
     
      unless line == 0
      to_evaluate = line_item.split("\n")[0]
        csv_values = to_evaluate.split(",")
        @line_items << {:type => csv_values[0], :description => csv_values[1], :quantity => csv_values[2], :unit_price => csv_values[3], :amount => csv_values[4]}
      end
      line += 1
    end


    @client_id = @full_invoice["client_id"]

    response = @connection.request "/clients/#{@client_id.to_s}", :get
    @client = JSON.parse(response.body)
    
    @client_id = @full_invoice["client_id"]
     


    
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/create.html.erb
<h3> Invoices for Company <%= @company.capitalize %></h3>

<% my_counter = 0 %>
  <table>
      <tr>
        <th>Status</th>
        <th>Invoice number</th>
        <th>Client</th>
        <th> Description</th>
        <th>Quantity</th>
        <th>Unit Price</th>
        <th>Amount</th> 
      </tr>

<% @invoice_details.each do |detail| %>

    <% my_counter += 1 %>

    <% full_detail = detail[:full_invoice]%>
  
    
    <% parts = full_detail.split("\n") %>
    <% part_1 = parts[1] %>

    <% parts2 = part_1.split(",") %>
    

      <tr>
     <% if detail[:status] == "overdue" %>
       <td class="overdue"> <b><%= link_to "Overdue", report_path(:id => detail[:id]) %></b></td>
     <% else %>
       <td><%= link_to "Current", report_path(:id => detail[:id]) %></td>
    <% end %>
        <td class="invoice_number"><%= detail[:invoice_number] %> </td>
        <td class="client_name"><%= detail[:name] %></td>
         <td class="description"><%= parts2[1] %></td>
         <td class="quantity"><%= parts2[2] %></td>
         <td class="unit_price">$ <%= parts2[3] %></td>
        <td class="amount">$ <%= detail[:total_amount] %></td>
      </tr>

<% end %>
    </table>

app/views/reports/index.html.erb
<h1>Set Credentials</h1>

<%= form_for "report",  :url => reports_path, :html => {:method => :post} do |f| %>

<p>Please log in.</p>

<table>
  <tr>
    <th width="10%"><label for="user_name">Login:</label></th>
    <td><%= f.text_field 'login', :size => 30 %></td>
  </tr>
  
  <tr>
    <th><label for="password">Password:</label></th>
    <td><%= f.password_field 'password', :size => 30 %></td>
  </tr>

  <tr>
    <th><label for="remember_me">Company:</label></th>
   <td><%= f.text_field 'company', :size => 30 %></td>
  </tr>
</table>


<p><%= f.submit 'Get Report' %></p>
<% end -%>

app/views/reports/show.html.erb
<div style="width:1000px;">
  <div style="float:right;">
    <table>
    
      <tr>
      
      </tr>
    </table>
  </div>
  
  <div style="float:left;">
    <table >
      <tr>
        <td>
          <h1>INVOICE</h1>
        </td>
        <td>
        </td>
        <td style="width:600px;"></td>
        <td>
          From | <b><%=  @company %> </b>
        </td>
      </tr>
      <tr>
        
        <td>
          Invoice ID
        </td>
        <td>
          <%= @full_invoice["number"] %>
        </td>
        <td style="width:600px;"></td>
        <td>
          Invoice For | <%= @client["client"]["name"]%>
        </td>
      </tr>
      <tr>
        <td>
          Issue Date
        </td>
        <td>
          <%= @full_invoice["issued_at"] %>
        </td>
      </tr>
      <tr>
        <td>
          Due Date
        </td>
        <td>
          <%= @full_invoice["due_at_human_format"] %>
        </td>
    </table>
  </div>
</div>
<div style="clear:both;"></div>
<div style="float:left;">
  <table class="results" cellpadding=5, cellspacing=0>
    <tr>
      <th class="type">Type</th>
      <th class="description">Description</th>
      <th class="quantity">Quantity</th>
      <th class="unit_price">Unit Price</th>
      <th class="amount">Amount</th>
    </tr>
    
    <% @line_items.each do |line_item| %>
      <tr>
       <td class="type"><%= line_item[:type] %></td>
       <td class="description"><%= line_item[:description] %></td>
       <td class="quantity"> <%= line_item[:quantity] %></td>
       <td class="unit_price">$ <%= line_item[:unit_price] %></td>
       <td class="amount">$ <%= line_item[:amount]%></td>
     </tr>
    <% end %>

  </table>
  
  <table class="total">
    <tr>
      <th>Amount Due</th>
      <th>$ <%= @full_invoice["amount"] %></th>
      
    </tr>
    
  </table>
</div>